//user auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//seller auth
export const SELLER_REGISTER_SUCCESS = "SELLER_REGISTER_SUCCESS";
export const SELLER_REGISTER_FAIL = "SELLER_REGISTER_FAIL";
export const SELLER_LOGIN_SUCCESS = "SELLER_LOGIN_SUCCESS";
export const SELLER_LOGIN_FAIL = "SELLER_LOGIN_FAIL";
export const SELLER_LOGOUT = "SELLER_LOGOUT";
export const SELLER_USER_LOADED = "SELLER_USER_LOADED";
export const SELLER_AUTH_ERROR = "SELLER_AUTH_ERROR";
export const SELLER_CLEAR_ERRORS = "SELLER_CLEAR_ERRORS";
